In [1]:
import numpy as np
import torch

## torch.view 是交替出现，还是连续出现

我的理解：只是把数据的维度进行了变化，而数据的`先后顺序`以及`总的数据量`还是一致的

In [2]:
arr = torch.Tensor([[1]*16, [2]*16])
print(arr.shape)
arr

torch.Size([2, 16])


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [3]:
arr.view(-1)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
        2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [4]:
arr.view(-1, 16)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

## Group Query Attention

num_key_value_heads 维度上的重复是逐个相间的：
- 首先取原张量中的第一个"key-value head"并重复它
- 然后取第二个，并重复它，依此类推

In [40]:
x = torch.ones(2, 4, 4)
x[1] *= 2


In [41]:
n_rep = 2
hidden_states = x
shape_1 = hidden_states.shape

num_key_value_heads, slen, head_dim = hidden_states.shape

hidden_states
hidden_states = hidden_states[:, None, :, :].expand(num_key_value_heads, n_rep, slen, head_dim)
shape_2 = hidden_states.shape

hidden_states = hidden_states.reshape(shape_2[0] * shape_2[1], shape_2[2], shape_2[3])
print(f"{x.shape} -> {shape_1} -> {shape_2} -> {hidden_states.shape}")
hidden_states

torch.Size([2, 4, 4]) -> torch.Size([2, 4, 4]) -> torch.Size([2, 2, 4, 4]) -> torch.Size([4, 4, 4])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])

In [39]:
torch.allclose(hidden_states[0], hidden_states[1]), torch.allclose(hidden_states[2], hidden_states[3])

(True, True)

## ？

In [4]:
x = torch.ones(2, 4, 4)
x.numpy().tolist()

[[[1.0, 1.0, 1.0, 1.0],
  [1.0, 1.0, 1.0, 1.0],
  [1.0, 1.0, 1.0, 1.0],
  [1.0, 1.0, 1.0, 1.0]],
 [[1.0, 1.0, 1.0, 1.0],
  [1.0, 1.0, 1.0, 1.0],
  [1.0, 1.0, 1.0, 1.0],
  [1.0, 1.0, 1.0, 1.0]]]